name: Sync main -> major_rc

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Merge main -> major_rc
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: main
          target_branch: major_rc
          github_token: ${{ secrets.GITHUB_TOKEN }}
