name: Sync branches

on:
  workflow_dispatch:

jobs:
  merge-ta_mirage-to-major_rc_mirage:
    name: Merge ta_mirage to major_rc_mirage
    runs-on: ubuntu-latest
    steps:

      - name: Merge ta_mirage -> major_rc_mirage
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: ta_mirage
          target_branch: major_rc_mirage
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: major_rc_mirage

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
          cache-dependency-path: 'my-app/pom.xml'

      - name: Build with Maven
        run: mvn -f my-app/pom.xml --batch-mode --update-snapshots test


  merge-major_rc-to-major_rc_mirage:
    name: Merge major_rc to major_rc_mirage
    runs-on: ubuntu-latest
    steps:

      - name: Merge major_rc -> major_rc_mirage
        uses: ppotapkin/merge-branch@v0.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_branch: major_rc
          target_branch: major_rc_mirage

      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: major_rc_mirage

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
          cache-dependency-path: 'my-app/pom.xml'

      - name: Build with Maven
        run: mvn -f my-app/pom.xml --batch-mode --update-snapshots test